ControleJogo/ControleJogo/Controllers/ConsolesController.cs
using ControleJogo.Aplicacao.InputModel;
using ControleJogo.Aplicacao.Services;
using ControleJogo.Extensions;
using ControleJogo.Infra.DatabaseRead.DataAcess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControleJogo.Controllers
{
    [Authorize]
    public class ConsolesController : Controller
    {
        private readonly IConsoleDataRead read;
        private readonly IConsoleAppService service;

        public ConsolesController(IConsoleDataRead read, IConsoleAppService service)
        {
            this.read = read;
            this.service = service;
        }

        public async Task<ActionResult> Index()
        {
            return View(await read.BuscarTodos());
        }

        public async Task<ActionResult> Details(Guid id)
        {
            return View((await read.BuscarPeloId(id)).ConvertTo<ConsoleViewModel>());
        }

        public ActionResult Create()
        {
            return View(new ConsoleViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ConsoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                model = await service.Adicionar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(Guid id)
        {
            return View((await read.BuscarPeloId(id)).ConvertTo<ConsoleViewModel>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ConsoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                model = await service.Atualizar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            return View((await read.BuscarPeloId(id)).ConvertTo<ConsoleViewModel>());
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(Guid id)
        {
            var model = (await read.BuscarPeloId(id)).ConvertTo<ConsoleViewModel>();
            model = await service.Remover(model);

            if (model.ValidationResult.IsValid)
                return RedirectToAction("Index");

            foreach (var item in model.ValidationResult.Errors)
            {
                ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
            }
            return View(model);
        }
    }
}

ControleJogo/ControleJogo/Views/Consoles/Create.cshtml
@model ControleJogo.Aplicacao.InputModel.ConsoleViewModel
@{
    ViewBag.Title = "Novo";
}

<h2>Novo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Conole</h4>
        <hr />
        @Html.Partial("_ValidationSummary")

        @Html.HiddenFor(t => t.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Consoles", htmlAttributes: new { @class = "btn btn-default" })
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ControleJogo/ControleJogo/Views/Consoles/Delete.cshtml
@model ControleJogo.Aplicacao.InputModel.ConsoleViewModel

@{
    ViewBag.Title = "Remover";
}

<h2>Remover</h2>

<h3>Deseja realmente remover esse console?</h3>
<div>
    <h4>Console</h4>
    <hr />

    @Html.Partial("_ValidationSummary")

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Remover" class="btn btn-danger" />
            </div>
        </div>
    }
</div>

<br />
<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Consoles", htmlAttributes: new { @class = "btn btn-default" })
</div>

ControleJogo/ControleJogo/Views/Consoles/Details.cshtml
@model ControleJogo.Aplicacao.InputModel.ConsoleViewModel

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Console</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-info" })
        </div>
    </div>

</div>


<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Consoles", htmlAttributes: new { @class = "btn btn-default" })
</div>

ControleJogo/ControleJogo/Views/Consoles/Edit.cshtml
@model ControleJogo.Aplicacao.InputModel.ConsoleViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar Console</h4>
        <hr />
        @Html.Partial("_ValidationSummary")
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Consoles", htmlAttributes: new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleJogo/ControleJogo/Views/Consoles/Index.cshtml
@model IEnumerable<ControleJogo.Infra.DatabaseRead.OutputModel.ConsoleDTO>

@{
    ViewBag.Title = "Consoles";
}

<h2>Consoles</h2>

@{
    if (Request.IsAuthenticated)
    {
        <p>
            @Html.ActionLink("Novo Console", "Create")
        </p>
    }
}

<table class="table table-striped table-hover" id="tableConsoles">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th style="width:150px;">

            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td style="width:150px;">
                    <a href="@Url.Action("Details", new { id = item.Id })" data-modal="" class="btn btn-default">
                        <span title="Detalhes" class="glyphicon glyphicon-info-sign"></span>
                    </a>
                    @{
                        if (Request.IsAuthenticated)
                        {
                            <a href="@Url.Action("Edit", new { id = item.Id })" data-modal="" class="btn btn-info">
                                <span title="Editar" class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a href="@Url.Action("Delete", new { id = item.Id })" data-modal="" class="btn btn-danger">
                                <span title="Remover" class="glyphicon glyphicon-trash"></span>
                            </a>
                        }
                    }
                </td>
            </tr>
                        }
    </tbody>

</table>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#tableConsoles').tablesorter();
        })
    </script>
}