ControleJogo/ControleJogo/Controllers/AmigosController.cs
using ControleJogo.Aplicacao.InputModel;
using ControleJogo.Aplicacao.Services;
using ControleJogo.Extensions;
using ControleJogo.Infra.DatabaseRead.DataAcess;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ControleJogo.Controllers
{
    [Authorize]
    public class AmigosController : Controller
    {
        readonly IAmigoDataRead read;
        readonly IAmigoAppService service;
        readonly IEmprestimoJogoDataRead emprestimoRead;

        public AmigosController(IAmigoDataRead read, IAmigoAppService service, IEmprestimoJogoDataRead emprestimoRead)
        {
            this.read = read;
            this.service = service;
            this.emprestimoRead = emprestimoRead;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            return View(await read.BuscarTodos());
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var amigo = await read.BuscarPeloId(id);
            return View(amigo.ConvertTo<AmigoViewModel>());
        }

        public ActionResult Create()
        {
            return View(new AmigoViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AmigoViewModel model)
        {
            if (ModelState.IsValid)
            {
                model = await service.Adicionar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(Guid id)
        {
            var amigo = await read.BuscarPeloId(id);
            return View(amigo.ConvertTo<AmigoViewModel>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AmigoViewModel model)
        {
            if (ModelState.IsValid)
            {
                model = await service.Atualizar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var amigo = await read.BuscarPeloId(id);
            return View(amigo.ConvertTo<AmigoViewModel>());
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(Guid id)
        {
            var model = (await read.BuscarPeloId(id)).ConvertTo<AmigoViewModel>();
            model = await service.Remover(model);

            if (model.ValidationResult.IsValid)
                return RedirectToAction("Index");

            foreach (var item in model.ValidationResult.Errors)
            {
                ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<PartialViewResult> ObterEmprestimosParaAmigo(Guid Id)
        {
            return PartialView("~/Views/Emprestimos/_emprestimo.cshtml", await emprestimoRead.BuscarTodosParaAmigo(Id));
        }
    }
}

ControleJogo/ControleJogo/Controllers/JogosController.cs
using ControleJogo.Aplicacao.InputModel;
using ControleJogo.Aplicacao.Services;
using ControleJogo.Extensions;
using ControleJogo.Infra.DatabaseRead.DataAcess;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControleJogo.Controllers
{
    [Authorize]
    public class JogosController : Controller
    {
        readonly IJogoDataRead read;
        readonly ICategoriaDataRead categoriaRead;
        readonly IConsoleDataRead consoleRead;
        readonly IJogoAppService service;
        readonly IEmprestimoJogoDataRead emprestimoRead;

        public JogosController(IJogoDataRead read, ICategoriaDataRead categoriaRead, IConsoleDataRead consoleRead, IJogoAppService service, IEmprestimoJogoDataRead emprestimoRead)
        {
            this.read = read;
            this.categoriaRead = categoriaRead;
            this.consoleRead = consoleRead;
            this.service = service;
            this.emprestimoRead = emprestimoRead;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            return View(await read.BuscarTodos());
        }

        public async Task<ActionResult> Details(Guid id)
        {
            return View(await read.BuscarPeloId(id));
        }

        public async Task<ActionResult> Create()
        {
            ViewBag.Categorias = (await categoriaRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            ViewBag.Consoles = (await consoleRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            return View(new JogoViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(JogoViewModel model, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if(image != null && image.ContentLength > 0 && image.ContentType == "image/png")
                {
                    byte[] buffer = new byte[image.ContentLength];
                    using (BufferedStream stream = new BufferedStream(image.InputStream))
                    {
                        await stream.ReadAsync(buffer, 0, buffer.Length);
                    }
                    model.FotoJogo = buffer;
                }

                model = await service.Adicionar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            ViewBag.Categorias = (await categoriaRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            ViewBag.Consoles = (await consoleRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            return View(model);
        }

        public async Task<ActionResult> Edit(Guid id)
        {
            ViewBag.Categorias = (await categoriaRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            ViewBag.Consoles = (await consoleRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            return View((await read.BuscarPeloId(id)).ConvertTo<JogoViewModel>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(JogoViewModel model, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0 && image.ContentType == "image/png")
                {
                    byte[] buffer = new byte[image.ContentLength];
                    using (BufferedStream stream = new BufferedStream(image.InputStream))
                    {
                        await stream.ReadAsync(buffer, 0, buffer.Length);
                    }
                    model.FotoJogo = buffer;
                }
                else
                    model.FotoJogo = await read.CarregarImagem(model.Id); //Garantir que a imagem não seja apagada caso outra não for informada

                model = await service.Atualizar(model);

                if (model.ValidationResult.IsValid)
                    return RedirectToAction("Index");

                foreach (var item in model.ValidationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            ViewBag.Categorias = (await categoriaRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            ViewBag.Consoles = (await consoleRead.BuscarTodos()).Select(t => new SelectListItem() { Text = t.Descricao, Value = t.Id.ToString() }).ToList();
            return View(model);
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            return View(await read.BuscarPeloId(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(Guid Id)
        {
            var model = (await read.BuscarPeloId(Id)).ConvertTo<JogoViewModel>();
            model = await service.Remover(model);

            if (model.ValidationResult.IsValid)
                return RedirectToAction("Index");

            foreach (var item in model.ValidationResult.Errors)
            {
                ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
            }
            return View(await read.BuscarPeloId(Id));
        }

        [HttpGet()]
        [AllowAnonymous]
        [Route("ObterFotoJogo")]
        public async Task<FileContentResult> ObterFotoJogo(Guid Id)
        {
            var imagemJogo = await read.CarregarImagem(Id);
            if (imagemJogo != null && imagemJogo.Length > 0)
                return File(imagemJogo, "image/png");
            else
                return File(System.IO.File.ReadAllBytes(Server.MapPath(Url.Content("~/Content/Image/FotoGameNotFound.png"))), "image/png");
        }

        [HttpGet]
        public async Task<PartialViewResult> ObterEmprestimosParaJogo(Guid Id)
        {
            return PartialView("~/Views/Emprestimos/_emprestimo.cshtml", await emprestimoRead.BuscarTodosParaJogo(Id));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<PartialViewResult> ObterTopJogos()
        {
            return PartialView("_topJogosEmprestados", await emprestimoRead.TopMaisEmprestados());
        }
    }
}

ControleJogo/ControleJogo/Views/Jogos/Create.cshtml
@model ControleJogo.Aplicacao.InputModel.JogoViewModel

@{
    ViewBag.Title = "Novo";
}

<h2>Novo Jogo</h2>

@using (Html.BeginForm("Create", "Jogos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Novo Jogo</h4>
        <hr />
        @Html.Partial("_ValidationSummary")

        @Html.HiddenFor(t => t.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Imagem</label>
            <div class="col-md-10">
                <input id="image" name="image" type="file" value="" accept="image/png" class="form-control"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoriaId, ViewBag.Categorias as IEnumerable<SelectListItem>, "Selecione...",new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConsoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ConsoleId, ViewBag.Consoles as IEnumerable<SelectListItem>, "Selecione...", new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ConsoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantidadeJogos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantidadeJogos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantidadeJogos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Jogos", htmlAttributes: new { @class = "btn btn-default" })
</div>

ControleJogo/ControleJogo/Views/Jogos/Delete.cshtml
@model ControleJogo.Infra.DatabaseRead.OutputModel.JogoDTO

@{
    ViewBag.Title = "Remover";
}

<h2>Remover</h2>

<h3>Deseja realmente remover este jogo?</h3>
<div>
    <h4>Jogo</h4>
    <hr />
    
    @Html.Partial("_ValidationSummary")

    <div class="form-group">
        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nome)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nome)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoCategoria)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DescricaoCategoria)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoConsole)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DescricaoConsole)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Disponivel)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Disponivel)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.QuantidadeJogos)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantidadeJogos)
                </dd>
            </dl>
        </div>
        <div>
            <img src="@Url.Action("ObterFotoJogo", new { Id = Model.Id })" style="width:100px;height:100px;" />
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Remover" class="btn btn-danger" />
            </div>
        </div>
    }
</div>
<br />
<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Amigos", htmlAttributes: new { @class = "btn btn-default" })
</div>

ControleJogo/ControleJogo/Views/Jogos/Details.cshtml
@model ControleJogo.Infra.DatabaseRead.OutputModel.JogoDTO

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Jogo</h4>
    <hr />
    <div class="form-group">
        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nome)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nome)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoCategoria)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DescricaoCategoria)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DescricaoConsole)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DescricaoConsole)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Disponivel)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Disponivel)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.QuantidadeJogos)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantidadeJogos)
                </dd>
            </dl>
        </div>
        <div>
            <img src="@Url.Action("ObterFotoJogo", new { Id = Model.Id })" style="width:100px;height:100px;" />
        </div>
    </div>
    @{
        if (Request.IsAuthenticated)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-info" })
                </div>
            </div>
        }
    }

</div>

<div id="emprestimos">

</div>
<br/>

<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Jogos", htmlAttributes: new { @class = "btn btn-default" })
</div>

@section scripts{
    <script>
        $(function ()
        {
            $.get('@Url.Action("ObterEmprestimosParaJogo", new { Id = Model.Id})', function (data)
            {
                $('#emprestimos').html(data);
            });
        });
    </script>
}

ControleJogo/ControleJogo/Views/Jogos/Edit.cshtml
@model ControleJogo.Aplicacao.InputModel.JogoViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Jogos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Jogo</h4>
        <hr />
        @Html.Partial("_ValidationSummary")
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Imagem</label>
            <div class="col-md-10">
                <img src="@Url.Action("ObterFotoJogo", "Jogos", new { Id = Model.Id})" style="width:100px;height:100px;align-content:center;vertical-align:central;" class="img-responsive img-rounded" />
                <input id="image" name="image" type="file" value="" accept="image/png" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoriaId, ViewBag.Categorias as IEnumerable<SelectListItem>, "Selecione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConsoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ConsoleId, ViewBag.Consoles as IEnumerable<SelectListItem>, "Selecione...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConsoleId, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            @Html.LabelFor(model => model.QuantidadeJogos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantidadeJogos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantidadeJogos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à listagem", "Index", "Jogos", htmlAttributes: new { @class = "btn btn-default" })
</div>

ControleJogo/ControleJogo/Views/Jogos/Index.cshtml
@model IEnumerable<ControleJogo.Infra.DatabaseRead.OutputModel.JogoDTO>

@{
    ViewBag.Title = "Jogos";
}

<h2>Jogos</h2>

@{
    if (Request.IsAuthenticated)
    {
        <p>
            @Html.ActionLink("Novo Jogo", "Create")
        </p>
    }
}
<table class="table table-striped table-hover" id="tableJogos">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescricaoCategoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescricaoConsole)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.Disponivel)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.QuantidadeJogos)
            </th>
            <th>
                Imagem
            </th>
            <th style="width:150px;">

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescricaoCategoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescricaoConsole)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.Disponivel)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.QuantidadeJogos)
                </td>
                <td>
                    <img src="@Url.Action("ObterFotoJogo", new { Id = item.Id })"  style="width:100px;height:100px;" class="img-responsive img-rounded"/>
                </td>
                <td style="width:150px;">
                    @{
                        if (Request.IsAuthenticated)
                        {
                            <a href="@Url.Action("Details", new { id = item.Id })" data-modal="" class="btn btn-default">
                                <span title="Detalhes" class="glyphicon glyphicon-info-sign"></span>
                            </a>
                            <a href="@Url.Action("Edit", new { id = item.Id })" data-modal="" class="btn btn-info">
                                <span title="Editar" class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a href="@Url.Action("Delete", new { id = item.Id })" data-modal="" class="btn btn-danger">
                                <span title="Remover" class="glyphicon glyphicon-trash"></span>
                            </a>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#tableJogos').tablesorter();
        })
    </script>
}

ControleJogo/ControleJogo/Views/Jogos/_topJogosEmprestados.cshtml
@model IEnumerable<ControleJogo.Infra.DatabaseRead.OutputModel.TopEmprestados>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000" style="width:100%;height:75%;">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        @{
            for (int i = 0; i < Model.Count(); i++)
            {
                var item = Model.ElementAt(i);
                <div class="item @(i == 0 ? "active" : string.Empty)">
                    <img src="@Url.Action("ObterFotoJogo", "Jogos", new { Id = item.JogoId })" alt="@($"Jogo {item.NomeJogo}")" class="img-responsive" style="width:100%;height:250px;"/>
                    <div class="carousel-caption" role="option">
                        <h1 style="font-style:oblique;color:darkblue;" >
                            @item.NomeJogo
                        </h1>
                        <h3 style="font-style:oblique;color:steelblue">Total de emprestimos:@item.QuantidadeEmprestimos</h3>
                    </div>
                </div>
            }
        }
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Próximo</span>
    </a>
</div>